server:
  port: 8761

# ???? ???? discoveryservice?? ??? ??????
spring:
  application:
    name: discovery-service

# ??? ??. ????? ??. ???? ??? True. ??? ??? ???? ????? ??X
# Eureka ??? MS? ?? ??? ?? ??? ?? ??? ???????? ??.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false