server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///${user.home}/Desktop/config
          uri: https://github.com/seulseul2/spring-cloud-config
#          username: [your username]
#          password: [your password]