server:
  port: 0

spring:
  application:
    name: business-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/business-service?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root