server:
  port: 8020

spring:
  application:
    name: business-service
  jpa:
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://k7c105.p.ssafy.io:3306/lyra?serverTimezone=Asia/Seoul
    username: hermes
    password: Lyra@hanam^!3

#cloud:
#  aws:
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY_ID}       # AWS IAM AccessKey
#      secretKey: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey
#    s3:
#      bucket:  # 버킷 이름
#      dir:  # S3 디렉토리 이름
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k7c105.p.ssafy.io:8761/eureka