server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://k7c105.p.ssafy.io"
            allowedHeaders:
              - authorization
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - HEAD
              - DELETE

      routes:
#        일단은 회원정보 확인 인증없이 가능하게 만들었음, 나중에 수정 필요
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: business-service
          uri: lb://BUSINESS-SERVICE
          predicates:
            - Path=/business-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/business-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace