server:
  port: 8010

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://k7c105.p.ssafy.io"
            allowedHeaders:
              - authorization
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - HEAD
              - DELETE
  application:
    name: user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k7c105.p.ssafy.io:3307/lyra?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useLegacyDatetimeCode=false
    username: hermes
    password: Lyra@hanam^!3
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 679402942294-piour8km9qojcntfbm7h3n54qt63d1d9.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://k7c105.p.ssafy.io:8010/login/oauth2/code/google
          kakao:
            client-id: f42a76675ed8066de07e5cc3498f5c11
            client-secret: w0jxYoFytctR9tVqwTPh9tp90b5aEtsj
            client-authentication-method: post
            redirect-uri: http://k7c105.p.ssafy.io:8010/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://k7c105.p.ssafy.io:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans


#token:
#  expiration_time: 86400000
#  secret: user_token